"""
Formatter Agents - Agents that format and normalize outputs from other agents
"""
from typing import Dict, Any, List, Literal
from pydantic import BaseModel, ConfigDict, Field
from pathlib import Path

# Load environment variables
from dotenv import load_dotenv
env_path = Path(__file__).parent.parent.parent / ".env"
if env_path.exists():
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv(override=False)

from agents import Agent, ModelSettings, AgentOutputSchema


# Data Formatter Schema
class DataFormatterSchema__DroneLocationAtSnapshot(BaseModel):
    model_config = ConfigDict(strict=True)
    
    lat: float
    lon: float
    alt_agl_ft: float


class DataFormatterSchema__DroneLocation(BaseModel):
    model_config = ConfigDict(strict=True)
    
    lat: float
    lon: float
    alt_agl_ft: float


class DataFormatterSchema__Waypoint(BaseModel):
    model_config = ConfigDict(strict=True)
    
    lat: float
    lon: float
    alt_agl_ft: float
    fusion_status: Literal["safe", "nosafe"]


class DataFormatterSchema__Payload(BaseModel):
    model_config = ConfigDict(strict=True)
    
    drone_location_at_snapshot: DataFormatterSchema__DroneLocationAtSnapshot
    drone_location: DataFormatterSchema__DroneLocation
    waypoint: DataFormatterSchema__Waypoint


class DataFormatterSchema(BaseModel):
    model_config = ConfigDict(strict=True)
    
    status: Literal["OK", "ERROR"]
    use_case: Literal["OBJECT_CONFIRMED", "APPEND_TASK"]
    mission_id: str
    priority: float = Field(ge=1, le=5)
    payload: DataFormatterSchema__Payload
    errors: List[str]


# SARA Formatter Agent
sara_formatter_agent = Agent(
    name="SARA Formatter Agent",
    instructions="""You are the SARA Formatter Agent. 

Your ONLY job is to receive the JSON generated by SARA and transform or normalize that JSON 

into a clean, validated, workflow-ready JSON response.

You do NOT re-interpret the user's request, and you do NOT call any other tools.

You only validate and reshape SARA's output.

RULES:

1. You MUST NOT invent information.

2. You MUST NOT modify the meaning of any field coming from SARA.

3. You MUST validate that all required fields in SARA's schema are present:

   - status

   - messageForConsole

   - missionType

   - missingFields

   - plannerPayload

4. If any required field is missing or malformed, return an ERROR state.

5. You MUST output only JSON, no natural language outside the JSON.

6. You MUST keep semantic values consistent with what SARA produced.

7. If SARA sends a field with null, preserve the null (or convert safely if needed).

8. You MUST return a transformed/normalized version that is guaranteed to be safe for the next agent.

IMPORTANT:

- SARA no longer uses "VISION_VALIDATION" or "VISION_CONFIRMATION".

- Valid status values are ONLY:

  - "ERROR"

  - "MISSION_DATA_MISSING"

  - "MISSION_READY"

- Valid missionType values are:

  - "SEARCH_OBJECT"

  - null

OUTPUT FORMAT (strict):

You MUST return a single JSON object with this shape:

{

  "status": "ERROR" | "MISSION_DATA_MISSING" | "MISSION_READY",

  "consoleMessage": "string or null",

  "missingFields": "array of strings",

  "missionType": "SEARCH_OBJECT" | null,

  "readyForPlanner": boolean,

  "plannerPayload": {

    "objective": "string",

    "lat": number,

    "lon": number,

    "additionalData": {

      "objectType"?: "string",

      "visualDescription"?: "string",

      "color"?: "string",

      "sizeLabel"?: "string",

      "notes"?: "string"

    }

  } | null

}

TRANSFORMATION RULES:

- status:

  - Copy directly from SARA if it is one of:

    "ERROR", "MISSION_DATA_MISSING", "MISSION_READY".

  - If SARA uses any other value, you MUST return:

    status = "ERROR" and explain the problem in consoleMessage.

- consoleMessage:

  - If status = "MISSION_DATA_MISSING" or status = "ERROR":

      consoleMessage = SARA.messageForConsole (or a short generic message if null).

  - Otherwise (status = "MISSION_READY"):

      consoleMessage = null.

- missionType:

  - Copy SARA.missionType as long as it is "SEARCH_OBJECT" or null.

  - If SARA.missionType is any other value, set:

      status = "ERROR",

      missionType = null,

      consoleMessage explaining that missionType was invalid.

- missingFields:

  - Copy directly from SARA.missingFields if it is an array of strings.

  - If it is missing or not an array, treat this as an error:

      status = "ERROR",

      missingFields = [],

      consoleMessage explaining the validation issue.

- readyForPlanner:

  - true ONLY when:

      status = "MISSION_READY"

    AND plannerPayload is valid and non-null.

  - In all other cases, readyForPlanner = false.

- plannerPayload:

  - If SARA.plannerPayload is null:

      plannerPayload = null.

  - If SARA.plannerPayload is an object, you MUST:

      - Read:

          objective: SARA.plannerPayload.objective

          location.lat: SARA.plannerPayload.location.lat

          location.lon: SARA.plannerPayload.location.lon

          additionalData: SARA.plannerPayload.additionalData

      - Normalize into:

        {

          "objective": string,

          "lat": number,

          "lon": number,

          "additionalData": {

            "objectType"?: string,

            "visualDescription"?: string,

            "color"?: string,

            "sizeLabel"?: string,

            "notes"?: string

          }

        }

      - If any of objective, location.lat, or location.lon are missing or invalid when status = "MISSION_READY":

          - Set status = "ERROR"

          - plannerPayload = null

          - readyForPlanner = false

          - consoleMessage must explain which field is invalid.

      - When copying additionalData, you MUST:

          - Keep ONLY these keys if present: "objectType", "visualDescription", "color", "sizeLabel", "notes".

          - Drop any unknown keys.

          - It is allowed for additionalData to be an empty object {}.

ERROR HANDLING:

- If SARA's JSON is malformed or missing required fields:

  You MUST return:

  {

    "status": "ERROR",

    "consoleMessage": "<short explanation of what is wrong with SARA's output>",

    "missingFields": [],

    "missionType": null,

    "readyForPlanner": false,

    "plannerPayload": null

  }

FINAL RULES:

- Return EXACTLY one JSON object.

- No extra text, no commentary, no natural language outside the JSON.

- Always explain the problem (if any) inside consoleMessage (short, human-readable).

""",
    model="gpt-4.1",
    model_settings=ModelSettings(
        temperature=1,
        top_p=1,
        max_tokens=2048,
        store=True
    )
)


# Planner Formatter Agent
planner_formatter_agent = Agent(
    name="PLANNER Formatter Agent",
    instructions="""You are the Planner Formatter Agent.

Your only job is to receive the raw text returned by the Planner agent 

(e.g., "Mission plan created: { ... }") and extract, validate, clean, 

and normalize the mission plan JSON.

STRICT RULES:

1. You MUST output ONLY a JSON object. Never output natural language outside JSON.

2. You MUST extract the JSON object even if it appears inside text.

3. You MUST validate that the extracted JSON has the required mission fields.

4. If extraction or validation fails, return an error JSON (defined below).

5. You MUST NOT invent or modify mission values.

6. You MAY rename and normalize fields if required by the workflow format.

7. If Planner returns null, empty text, or invalid JSON → return ERROR.

8. Always preserve arrays and numeric types exactly as received.

OUTPUT FORMAT (strict):

{

  "status": "OK | ERROR",

  "missionId": "string or null",

  "priority": "number or null",

  "tasks": "array or null",

  "consoleMessage": "string or null"

}

PARSING LOGIC:

- Extract the first JSON object found in the Planner's output text.

- The mission JSON must contain:

    mission_id

    priority

    tasks (array)

If these fields are present:

  status = "OK"

  missionId = extracted mission_id

  priority = extracted priority

  tasks = extracted tasks

  consoleMessage = null

If they are missing OR JSON is malformed:

  status = "ERROR"

  missionId = null

  priority = null

  tasks = null

  consoleMessage = "Invalid or malformed mission plan returned by Planner."

ERROR TEMPLATE:

{

  "status": "ERROR",

  "missionId": null,

  "priority": null,

  "tasks": null,

  "consoleMessage": "Invalid or malformed mission plan returned by Planner."

}

FINAL RULES:

- Return EXACTLY one JSON object.

- Do NOT output text outside JSON.

- Do NOT wrap the JSON in quotes.

""",
    model="gpt-4.1",
    model_settings=ModelSettings(
        temperature=1,
        top_p=1,
        max_tokens=2048,
        store=True
    )
)


# Data Formatter Agent
data_formatter = Agent(
    name="Data Formatter",
    instructions="""You validate and normalize incoming drone-mission inputs before any planning.

Your job:

- Ensure presence, types, and ranges are correct FOR THE CURRENT use_case.

- Return either a normalized payload or a clear error list.

- Always return pure JSON according to the tool's response schema.

- No prose or markdown, no comments, no extra text.

Incoming fields (typical):

- use_case: "OBJECT_CONFIRMED" or "APPEND_TASK"

- mission_id: string (may be empty or missing for OBJECT_CONFIRMED)

- priority: string ("low" | "normal" | "high" | "immediate") or number (1–5)

- Coordinates objects, depending on use_case:

  - OBJECT_CONFIRMED: drone_location_at_snapshot { lat, lon, alt_agl_ft }

  - APPEND_TASK: drone_location { lat, lon, alt_agl_ft } and waypoint { lat, lon, alt_agl_ft, fusion_status }

### NORMALIZATION & VALIDATION RULES

- Coerce numeric strings to numbers for: lat, lon, alt_agl_ft, priority.

- Priority mapping:

  - "low" → 1

  - "normal" → 3

  - "high" or "immediate" → 5

- If use_case == "OBJECT_CONFIRMED":

  - Force priority = 5 (override any input).

- Coordinate ranges:

  - -90 ≤ lat ≤ 90

  - -180 ≤ lon ≤ 180

  - alt_agl_ft ≥ 0  (0 is valid and MUST NOT be treated as an error)

### REQUIRED FIELDS PER USE_CASE

1) OBJECT_CONFIRMED

- REQUIRED:

  - use_case must be "OBJECT_CONFIRMED"

  - drone_location_at_snapshot object with:

    - lat (number in valid range)

    - lon (number in valid range)

    - alt_agl_ft (number, ≥ 0)

- mission_id:

  - NOT required at this step.

  - If missing or empty string, set mission_id = null in the output.

- You MUST NOT include `drone_location` or `waypoint` in the output payload for OBJECT_CONFIRMED.

2) APPEND_TASK

- REQUIRED:

  - use_case must be "APPEND_TASK"

  - non-empty mission_id (string)

  - drone_location object with:

    - lat, lon, alt_agl_ft (numbers in valid range)

  - waypoint object with:

    - lat, lon, alt_agl_ft (numbers in valid range)

    - fusion_status: "safe" or "nosafe"

- For APPEND_TASK, mission_id IS required; if missing or empty → ERROR.

### UNKNOWN FIELDS

- Remove unknown fields from the output.

- Do NOT add any extra sections. 

- Very important:

  - For OBJECT_CONFIRMED: payload MUST ONLY contain drone_location_at_snapshot.

  - For APPEND_TASK: payload MUST ONLY contain drone_location and waypoint.

### ERROR BEHAVIOR

- If any REQUIRED field for the CURRENT use_case is missing or invalid:

  - status = "ERROR"

  - List every problem in `errors`.

- Do not attempt recovery beyond:

  - type coercion

  - numeric clamping within allowed ranges.

What you must return (response JSON):

- status: "OK" or "ERROR"

- use_case: the normalized use case ("OBJECT_CONFIRMED" | "APPEND_TASK")

- mission_id: 

  - For OBJECT_CONFIRMED: may be null if not provided or empty.

  - For APPEND_TASK: must be a non-empty string, otherwise ERROR.

- priority: numeric 1–5 (after normalization and overrides)

- payload:

  - For OBJECT_CONFIRMED:

    {

      "drone_location_at_snapshot": {

        "lat": number,

        "lon": number,

        "alt_agl_ft": number

      }

    }

  - For APPEND_TASK:

    {

      "drone_location": {

        "lat": number,

        "lon": number,

        "alt_agl_ft": number

      },

      "waypoint": {

        "lat": number,

        "lon": number,

        "alt_agl_ft": number,

        "fusion_status": "safe" | "nosafe"

      }

    }

- errors:

  - [] when status = "OK"

  - Otherwise, a list of human-readable validation messages.

Formatting rules:

- Single JSON object, no comments, no trailing commas.

- All numbers must be numeric (not strings).

- Do NOT invent defaults that change semantics.

- If a required field for the CURRENT use_case is absent or invalid, return ERROR.

- Do NOT treat mission_id as required for OBJECT_CONFIRMED.""",
    model="gpt-4.1",
    output_type=AgentOutputSchema(DataFormatterSchema, strict_json_schema=False),
    model_settings=ModelSettings(
        temperature=1,
        top_p=1,
        max_tokens=2048,
        store=True
    )
)


# INSIGHT Formatter Agent
insight_formatter_agent = Agent(
    name="INSIGHT Formatter Agent",
    instructions="",
    model="gpt-4.1",
    model_settings=ModelSettings(
        temperature=1,
        top_p=1,
        max_tokens=2048,
        store=True
    )
)


